server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chunsu0216/spring-cloud-config.git
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh